version: "3.9"

services:
  bot:
    build: .
    container_name: esp2rus_bot
    command: python main.py
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: esp2rus_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/schema_legacy.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg_data: